# Generated by Django 4.1.1 on 2022-09-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_stars_post_type_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nikname', models.CharField(max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(max_length=69)),
                ('stars', models.IntegerField(max_length=5)),
            ],
        ),
    ]
